zeitraum_tage: 90
search_url: https://api-touren-termine.adfc.de/api/eventItems/search
get_event_url: https://api-touren-termine.adfc.de/api/eventItems/
static_search_params:
  limit: "10000"
  includeSubsidiary: "true"
  sort: "date"
  fromNow: "false"
  eventType: Radtour
units:
  - name: Hamburg
    key: 158
  - name: Cuxhaven
    key: 162260
  - name: Pinneberg
    key: 170190
  - name: LK Harburg
    key: 162270
  - name: Uelzen
    key: 162291
  - name: Lüneburg
    key: 162290
  - name: Neumüsnter
    key: 170160
  - name: Schwerin
    key: 140004
  - name: Lauenburg
    key: 170130
  - name: Lüchow Dannenberg
    key: 162280
  - name: Bad Segeberg
    key: 170230
  - name: Stade
    key: 162330
  - name: Steinburg
    key: 170240
  - name: Storman
    key: 170291
  - name: Heidekreis
    key: 162320
  - name: Ostholtstein
    key: 170180
  - name: Rotenburg
    key: 162310
# Zum Testen: In Dresden gibt es Touren die etwas kosten.
#  - name: Dresden
#    key: 142002
